#!/bin/bash

source ./settings

pickdrafts() {
oldIFS=$IFS
IFS=$' '
choices=( `ls $DRAFTDIR` )
IFS=$oldIFS
PS3="Draft to post: "
select answer in "${choices[@]}"; do
  for item in "${choices[@]}"; do
  if [[ $item == $answer ]]; then
 break 2
   fi
  done
  done
  chosen=$answer
  echo "$chosen"
  if [[ -z "$chosen" ]]; then echo "Put a draft in "$DRAFTDIR" to use bs.">&2; kill $$; fi
}

hidedraft() {
mv $DRAFTDIR$drafttopost $DRAFTDIR.$drafttopost
echo "note: the draft file has been hidden, it is still in the drafts folder"
}

postdraft() {
echo "making sure '"$BLOGDIR"' and other nessesary directories exist..."
mkdir -p $TMPDIR
mkdir -p $BLOGDIR
echo "converting title to human readable..."
htitle=`echo $drafttopost | sed 's/-/ /g'`
echo "title is '"$htitle"'. press CTRL+c NOW if it is wrong"
echo "you have 1 second before it moves on to perminent changes"
sleep 1
echo "generating metadata"
permalink=$BLOGDIR`echo $drafttopost | head -c $URLLEN`".html"
desc=`cat $DRAFTDIR$drafttopost | head -c $DSCLEN`
content=`cat $DRAFTDIR$drafttopost`

echo "generating temporary files ("$tmpuuid")"
cat templates/post_ex.html | sed -z "
s/<\!-- bs title -->/$htitle/g;
s/<\!-- bs date -->/$PUBDATE/g;
s/<\!-- bs desc -->/$desc/g;
s+<\!-- bs link -->+$permalink+g" > $TMPDIR/ex.html
cat templates/rss_ex.xml | sed -z "
s/<\!-- bs title -->/$htitle/g;
s/<\!-- bs date -->/$PUBDATE/g;
s/<\!-- bs desc -->/$desc/g;
s+<\!-- bs link -->+$URL$permalink+g" > $TMPDIR/ex.xml

echo "copying files to correct locations"
sed -i "/<\!-- bs insert -->/r $TMPDIR/ex.html" $INDEX
sed -i "/<\!-- bs insert -->/r $TMPDIR/ex.xml" $RSS
cat templates/post.html | sed -z "
s/<\!-- bs title -->/$htitle/g;
s/<\!-- bs date -->/$PUBDATE/g;
s/<\!-- bs content -->/$content/g;" > $permalink
}

cat <<EOF
 _         
| |__  ___ 
| '_ \\/ __|
| |_) \\__ \\
|_.__/|___/
LickTheCheese's Blog Script
	   
EOF
echo "ecit a text file in "$DRAFTDIR" to make a new draft"
echo "seperate words with hyphens ( - ) to make the title."
echo
echo "edit ./settings for some settings"
echo
echo "Pick a draft to post or press CTRL+c"
drafttopost=`pickdrafts`
postdraft
hidedraft


