#!/bin/bash

tmpuuid=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5`

# paths config
export INDEX="index.html"
export RSS="rss.xml"
export BLOGDIR='p/'`date +%Y/%b`"/"
export DRAFTDIR=".drafts/"
export TMPDIR="/tmp/bs/"$tmpuuid

# metadata config
export URLLEN=20
export DSCLEN=200
export PUBDATE=`date '+%b %d, %Y'`
export URL="https://thepeachtimes.github.io/"


